services:
  taxi_service_backend_dev:
    container_name: taxi-service-backend-dev
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/backend/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - taxi_service_db_dev
    networks:
      - taxi_service_network_dev

  taxi_service_db_dev:
    image: postgres:15
    container_name: taxi-service-db-dev
    volumes:
      - taxi_service_postgres_data_dev:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5433:5432
    networks:
      - taxi_service_network_dev

  taxi_service_redis_dev:
    image: redis:7.2
    container_name: taxi-service-redis-dev
    networks:
      - taxi_service_network_dev

  taxi_service_celery_worker_dev:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    container_name: taxi-service-celery-worker-dev
    env_file:
      - .env
    command: celery -A config worker --concurrency=3 --loglevel DEBUG -P threads
    depends_on:
      - taxi_service_redis_dev
      - taxi_service_db_dev
    networks:
      - taxi_service_network_dev

  taxi_service_celery_beat_dev:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    container_name: taxi-service-celery-beat-dev
    env_file:
      - .env
    command: celery -A config beat --pidfile= --loglevel DEBUG
    depends_on:
      - taxi_service_redis_dev
      - taxi_service_db_dev
    networks:
      - taxi_service_network_dev

volumes:
  taxi_service_postgres_data_dev:
networks:
  taxi_service_network_dev:
